---
title: "Work Group Meeting 3"
author: "Fundamental Techniques in Data Science with R"
date: "December 1, 2022"
output:
  ioslides_presentation:
    logo: UU_logo.jpg
    smaller: yes
    widescreen: no
---

<style>
h2{
  color: black;
}

h3{
  color: black;
  font-family: "Rockwell";
  text-align: left;
}

h4{
  color: grey;
  font-family: "Rockwell";
  text-align: left;
}

.forceBreak { -webkit-column-break-after: always; break-after: column; }

#centertext{
color: black;
text-align: center;
font-size: 35px; 
line-height:1.5em;
}

#othertext{
color: black;
text-align: left;
font-size: 20px; 
line-height:1.5em;
}

#thirdtext{
color: black;
text-align: left;
font-size: 28px; 
line-height:1em;
}


</style>

```{r setup, echo = FALSE, warning = FALSE}
library(ggplot2)
library(mvtnorm)
set.seed(235711)
theme_update(plot.background = element_rect(fill = "transparent", colour = NA))
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      dev.args = list(bg = "transparent"), 
                      fig.align = "center")
```


## This Workgroup Meeting

<h3> 1\. General comments on Individual Assignment </h3>
<h3> 2\. Forming groups </h3>
<h3> 3\. Pitching proposals </h3>
<h3> 4\. Present choices </h3>
<h3> 5\. Starting group assignment </h3>

## General comments - Individual Assignment

<h3> - Annotate code </h3>
<h3> - Write text to explain your steps </h3>
<h3> - Explain variables clearly (in text) </h3>
<h3> - Choose what to include <br> <tab> -> Use *head()*, *warnings=FALSE*, make tables </h3>
<h3> - Style plots, tables, text </h3>


## General comments - Individual Assignment

<h3> - Annotate code </h3>
<h3> - Write text to explain your steps </h3>
<h3> - Explain variables clearly (in text) </h3>
<h3> - Choose what to include <br> <tab> -> Use *head()*, *warnings=FALSE*, make tables </h3>
<h3> - Style plots, tables, text </h3>

<br><br>
<h3 style = "color: Blue"> - Name your .zip-file accordingly </h3>

## Forming Groups

<h3> - Groups consist of 3 to 4 students </h3>
<h3> - Both assignment 1 and 2 will be in these groups </h3>
<h3> - Forming groups with similar topics can help </h3>


## Formed a group? Pitch!


<h4> Pitch individual assignments (data, research questions), use the produced HTML</h4>

<br>
<h4> Evaluate each pitch</h4>

- Are data processing steps done correctly?
- Is the topic interesting and are the Research questions relevant? 

<h4> As a group, choose the data set(s) that you want to use for the assignments </h4>
<p id ="othertext"> Note that you can decide to select different data sets for Assignment 1 and Assignment 2 </p>

<br>
<p id="thirdtext"> Take 5 minutes for every person to present and discuss <br> (3 or 4 rounds) </p>


## Group Choices
<br><br>
<p id ="centertext"> Present the data set(s) you chose for the other groups </p>


## Assignment 1

<h4>You perform a multiple linear regression analysis in R and report this using R markdown. The assignment will be graded on the following four elements:</h4><br>

-	<b>Exploratory data analysis:</b> Introduction of your research questions, description and potential processing of your data. 
-	<b>Linear regression:</b> Description of the building process, the model fit, and the model comparison procedure.
-	<b>Assumptions:</b> Testing of model assumptions, checking for outliers and influential cases. Act upon and reflect on violations when needed.
-	<b>Interpretation:</b> Substantive interpretation of the final model. Answers to your research questions.
-	<b>Layout:</b> Structure of the document, output is efficiently presented, custom functions are developed when needed. Graphs are used where fitting. 

<b><u><em> Find the complete assignment description on the course web site.</em></u></b>

## Remainder of Meeting

<br><br>
<h4> - Send names of group members and preliminary RQs to teachers. </h4>
<h4> - Start on group assignment. </h4>
<h4> - Make agreements on how to work together. </h4>
<h4> - Improve the processing and visualization steps you did so far.</h4>
<h4> - The work so far can function as first sections.</h4>

<br><br>
<h3><u><em> After this meeting, continue to work on the assignment</em></u> </h3>

